import { Brand } from "@/types/brand";
import { Link2, Brain, Zap, Shield, Code2, Layers, Database, Rocket, Lock, TrendingUp } from "lucide-react";

const brandData: Brand[] = [
  {
    id: 1,
    name: "Unified Data Engine",
    href: "#features",
    image: "Database",
    description: "One platform for all data types",
    icon: Database,
    iconColor: "text-blue-600 dark:text-blue-400",
    bgGradient: "from-blue-50 via-blue-100 to-blue-200 dark:from-blue-900/30 dark:via-blue-800/30 dark:to-blue-700/30",
  },
  {
    id: 2,
    name: "AI-Native by Design",
    href: "#features",
    image: "Brain",
    description: "Built-in AI capabilities",
    icon: Brain,
    iconColor: "text-purple-600 dark:text-purple-400",
    bgGradient: "from-purple-50 via-purple-100 to-purple-200 dark:from-purple-900/30 dark:via-purple-800/30 dark:to-purple-700/30",
  },
  {
    id: 3,
    name: "High Performance",
    href: "#features",
    image: "Zap",
    description: "1.5M+ QPS with low latency",
    icon: Zap,
    iconColor: "text-yellow-600 dark:text-yellow-400",
    bgGradient: "from-yellow-50 via-yellow-100 to-yellow-200 dark:from-yellow-900/30 dark:via-yellow-800/30 dark:to-yellow-700/30",
  },
  {
    id: 4,
    name: "Enterprise Security",
    href: "#features",
    image: "Shield",
    description: "Zero-trust architecture",
    icon: Shield,
    iconColor: "text-green-600 dark:text-green-400",
    bgGradient: "from-green-50 via-green-100 to-green-200 dark:from-green-900/30 dark:via-green-800/30 dark:to-green-700/30",
  },
  {
    id: 5,
    name: "Developer First",
    href: "#features",
    image: "Code2",
    description: "Intuitive SDKs & APIs",
    icon: Code2,
    iconColor: "text-indigo-600 dark:text-indigo-400",
    bgGradient: "from-indigo-50 via-indigo-100 to-indigo-200 dark:from-indigo-900/30 dark:via-indigo-800/30 dark:to-indigo-700/30",
  },
  {
    id: 6,
    name: "Multi-Modal Support",
    href: "#features",
    image: "Layers",
    description: "Vector, Time-Series, Geo & more",
    icon: Layers,
    iconColor: "text-cyan-600 dark:text-cyan-400",
    bgGradient: "from-cyan-50 via-cyan-100 to-cyan-200 dark:from-cyan-900/30 dark:via-cyan-800/30 dark:to-cyan-700/30",
  },
  {
    id: 7,
    name: "Lightning Fast",
    href: "#features",
    image: "Rocket",
    description: "Sub-millisecond latency",
    icon: Rocket,
    iconColor: "text-orange-600 dark:text-orange-400",
    bgGradient: "from-orange-50 via-orange-100 to-orange-200 dark:from-orange-900/30 dark:via-orange-800/30 dark:to-orange-700/30",
  },
  {
    id: 8,
    name: "Data Privacy",
    href: "#features",
    image: "Lock",
    description: "Complete data sovereignty",
    icon: Lock,
    iconColor: "text-red-600 dark:text-red-400",
    bgGradient: "from-red-50 via-red-100 to-red-200 dark:from-red-900/30 dark:via-red-800/30 dark:to-red-700/30",
  },
  {
    id: 9,
    name: "Scalable Architecture",
    href: "#features",
    image: "TrendingUp",
    description: "Horizontal scaling built-in",
    icon: TrendingUp,
    iconColor: "text-emerald-600 dark:text-emerald-400",
    bgGradient: "from-emerald-50 via-emerald-100 to-emerald-200 dark:from-emerald-900/30 dark:via-emerald-800/30 dark:to-emerald-700/30",
  },
  {
    id: 10,
    name: "Seamless Integration",
    href: "#features",
    image: "Link2",
    description: "Connect with existing tools",
    icon: Link2,
    iconColor: "text-pink-600 dark:text-pink-400",
    bgGradient: "from-pink-50 via-pink-100 to-pink-200 dark:from-pink-900/30 dark:via-pink-800/30 dark:to-pink-700/30",
  },
];

export default brandData;
